# Site settings
name: Sylvestre Okafor
title: Sylvestre Okafor | Data Scientist
description: Descriptive Data Scientist focused on building ETL pipelines, and predictive models, beautiful dashboards and interactive user experiences
url: https://Sylvestre5.github.io/
baseurl: ''
email: sylvestreanderson5@gmail.com
cover: https://Sylvestre5.github.io/img/og.png
logo: https://Sylvestre5.github.io/img/emojis/technologist.png
resume: https://Sylvestre5.github.io/resume.pdf
social:
  - title: email
    url: mailto:sylvestreanderson5@gmail.com
  - title: twitter
    url: https://twitter.com/sylvestreanders
  - title: instagram
    url: https://instagram.com/slykeyzz
  - title: github
    url: https://github.com/sylvestre5
  - title: linkedin
    url: https://www.linkedin.com/in/ikenna-sylvestre-okafor-b7094296/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
